### ISSUE TITLE
Is the used data open source?

### ISSUE THREAD

**Issue by ashra-main** [Tesseract-MI/prostatecancer.ai#45]
Hi, I am really interested in improving the model and I was wondering about the dataset you have used? Is it accessible? if not could you provide some information on how it is collected? How many patients? how many with significant cancer? how it is annotated?

**Comment by sedghi** [comment]
Hi Arash, 
You can find this under options>about. 
In summary, we have used ProstateX challenge dataset which is publicly available. 
https://wiki.cancerimagingarchive.net/display/Public/SPIE-AAPM-NCI+PROSTATEx+Challenges
It has all the information you need.

**Comment by ashra-main** [comment]
Awesome. Thank you.
